### ISSUE TITLE
data-swipe-ignore doesn't work properly

### ISSUE THREAD

**Issue by cindro** [john-doherty/swiped-events#13] opened 2020-05-01 18:38 UTC
I like to load all my js at the bottom of the page like most people, but data-swipe-ignore is overwritten by the default false value. Below code only works if the js library is loaded before the div.

How can I get the ignore to work when the library is loaded last?

```
<div data-swipe-ignore="true">
     Swipe area
</div>
```

**Comment by john-doherty** [comment] 2020-08-29 10:51
Hi @cindro, please can you include an example [jsfiddle.net](https://jsfiddle.net/) so I can review this quickly?

**Comment by john-doherty** [comment] 2020-11-15 08:45
@cindro `data-swipe-ignore` is detected during a swipe event, it has nothing to do with how you load the script. I'm closing this as I'm unable to reproduce this, feel free to reopen with a code snippet if this is still an issue

**Closed as completed by john-doherty** 2020-11-15 08:45 UTC
